services:
  client:
    build: ./client
    ports:
      - "5432:80"
    environment:
      - REACT_APP_BASE_URL=http://192.168.1.188:5432
      - REACT_APP_API_BASE_URL=http://192.168.1.188:4321
    volumes:
      - ./client:/app

  server:
    build: ./server
    ports:
      - "4321:5000"
    environment:
      - DATABASE_URL=sqlite:///app.db
    volumes:
      - ./server:/app
